# Usamos una imagen base de MySQL en lugar de MongoDB
FROM mysql:latest

# Copiamos los archivos necesarios (si los hubiera)
# Si tienes scripts SQL u otros archivos que necesitas ejecutar al iniciar la base de datos, cárgalos aquí
# COPY ./tu_script.sql /docker-entrypoint-initdb.d/

# No es necesario establecer un WORKDIR si no necesitas trabajar dentro del contenedor
# WORKDIR /app
